version: "3.9"

services:
  postgres_latest:
    container_name: postgres_latest
    restart: always
    volumes:
      # database
      - ./postgres_latest:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Admin123*
    ports:
      - "5434:5432"